/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mariefurda
 */

import java.util.List;
import java.util.ArrayList;
    
public class OrderPage extends javax.swing.JPanel {

    /**
     * Creates new form OrderPage2
     */
    public OrderPage() {
        initComponents();
    }
    
    public String getToppings() {
         List<String> toppings = new ArrayList<String>();
		   
        if(jCheckBox1.isSelected()) {
            toppings.add(jCheckBox1.getText());
        }
        if(jCheckBox2.isSelected()) {
            toppings.add(jCheckBox2.getText());
        }
        if(jCheckBox3.isSelected()) {
            toppings.add(jCheckBox3.getText());
        }
        if(jCheckBox4.isSelected()) {
            toppings.add(jCheckBox4.getText());
        }
        if(jCheckBox5.isSelected()) {
            toppings.add(jCheckBox5.getText());
        }
        if(jCheckBox6.isSelected()) {
            toppings.add(jCheckBox6.getText());
        }
        if(jCheckBox7.isSelected()) {
            toppings.add(jCheckBox7.getText());
        }
        
        String toppingsString = toppings.toString();
        return toppingsString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(187, 45, 58));
        setForeground(new java.awt.Color(236, 219, 179));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Your Toppings:");

        jCheckBox1.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox1.setText("Banana Peppers");

        jCheckBox2.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox2.setText("Jalapenos");

        jCheckBox3.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox3.setText("Pepperoni");

        jCheckBox4.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox4.setText("Olives");

        jCheckBox5.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox5.setText("Anchovies");

        jCheckBox6.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox6.setText("Mushrooms");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox7.setText("Sausage");

        jCheckBox8.setFont(new java.awt.Font("Bebas Neue", 0, 17)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(236, 219, 179));
        jCheckBox8.setText("Extra Cheese");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pizza Texture (Large).jpg"))); // NOI18N
        jLabel8.setText("jLabel3");

        jProgressBar1.setValue(33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jCheckBox6)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jCheckBox3)
                                                    .addGap(30, 30, 30)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBox4)
                                                .addGap(53, 53, 53)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox8)
                                            .addComponent(jCheckBox5)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox2)))
                                    .addComponent(jCheckBox7))
                                .addGap(47, 47, 47)))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.getAccessibleContext().setAccessibleName("Pizza Container");
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
